git:
  depth: 1
language: node_js
addons:
  sauce_connect:
    username: "${SAUCE_LABS_USER}"
    access_key: "${SAUCE_LABS_AUTH_TOKEN}"
node_js:
  - '0.12'
cache:
  directories:
  - node_modules
  - jspm_packages
deploy:
  - provider: releases
    api_key: "${GITHUB_AUTH_TOKEN}"
    on:
      tags: true

  - provider: npm
    api_key: "${NPM_API_KEY}"
    on:
      tags: true}

