git:
  depth: 1
language: node_js
addons:
  sauce_connect: true
node_js:
  - '4.2'
before_script:
  - sudo setcap 'cap_net_bind_service=+ep' $(readlink -f $(which node))
cache:
  directories:
  - node_modules
  - jspm_packages
deploy:
  - provider: releases
    api_key: "${GITHUB_AUTH_TOKEN}"
    on:
      tags: true

  - provider: npm
    api_key: "${NPM_API_KEY}"
    on:
      tags: true

